### ISSUE TITLE
Windows Security app flagging excel-server.exe v4.0.3 & v4.0.4

### ISSUE THREAD

**Issue by dmorchard** [Aeraphe/xvba-repo#2]
Hey there!  Thanks for freeing us from the Excel VBA IDE :)   It's long overdue, and I'm keen to switch over to VSC permanently.

I'm having some trouble though.  It started with version 4.0.3 where Windows Security app detected Trojan:Win32/Zpevdo.B and quarantined excel-server.exe.

The same thing is happening with v4.0.4, but not when I roll back to v4.0.2.

I hope you're able to clear this up; I really want to keep using this plugin.

Cheers!

**Comment by goertzenator** [comment]
I helped @dmorchard with this issue and can confirm the 4.0.3 and 4.0.4 get flagged for trojans on my machine.  4.0.2 does not have this issue.  Window Security finds no other issues on my machine.

I do not use VBA myself or even have Excel installed on my computer.

**Comment by dmorchard** [comment]
Issue is no longer present in v4.0.7.  Thanks!

**Comment by Aeraphe** [comment]
This is a false positive antivirus alarme.
It happens VBScript ar converter to exe file.
Check on internet.

**Comment by Aeraphe** [comment]
This is a false positive antivirus alarme.
It happens VBScript ar converter to exe file.
Check on internet.
Hide quoted text
