### ISSUE TITLE
Error in AutoloadModules Subscript out of bounds

### ISSUE THREAD

**Issue by Kannnnng** [Aeraphe/xvba-repo#3]
I am a Chinese user, thank you for your outstanding work, but I encountered a problem in the process of using it. When I tried to upload the VBA code to Excel, the "excel-server" program gave me an error, " Error in AutoloadModules: Subscript out of bounds", I have uploaded a screenshot, please help to see what is causing the problem. In addition, this error will not only occur when using the upload code function, but also other operations will cause this error, and Prompting the error module has changed. For example, when I want to export the original VBA code in the Excel file, the error will become "Error in ExportModules: Subscript out of bounds".
The operating system I use is windows10 21H1, and Office is the 2019 home and student version.
![image](https://user-images.githubusercontent.com/22359680/119309932-9c1f8500-bca1-11eb-9642-dbc68af57d48.png)
![image](https://user-images.githubusercontent.com/22359680/119309945-a2adfc80-bca1-11eb-81ec-172e1f566684.png)

**Comment by Aeraphe** [comment]
Thanks for your email
I will check as soon as possible.
First I am moving to other city and try to find new job

See you.

**Comment by Kannnnng** [comment]
Okay, thank you again for your outstanding work

**Comment by Aeraphe** [comment]
Please check the excel macro config and then check the file name setting in
config.json.

[image: setup.gif]
[image: setup-confi.gif]

Em seg., 24 de mai. de 2021 às 22:45, 木叶 ***@***.***>
escreveu:

**Comment by Kannnnng** [comment]
Sorry, I can’t see the picture you uploaded, I think you should open the github webpage, and then upload the picture

**Comment by Kannnnng** [comment]
What i see is like this

![image](https://user-images.githubusercontent.com/22359680/119660618-0bdc6e00-be62-11eb-8dfa-2966afe18a5e.png)

**Comment by Aeraphe** [comment]
![setup](https://user-images.githubusercontent.com/19958617/119738997-f7937380-be57-11eb-8c8d-467ebc6b8b7c.gif)
![setup-confi](https://user-images.githubusercontent.com/19958617/119739032-00844500-be58-11eb-8196-a5fef25fb167.gif)

**Comment by Kannnnng** [comment]
I know where the problem lies. I added an extra "./" symbol to the configuration items of the file name and file path...
![image](https://user-images.githubusercontent.com/22359680/119762143-be9ee180-bedf-11eb-949c-3da1db22c8ca.png)
